### ISSUE TITLE
Actor gets ORomancePlayerWaitPackage stuck on them.

### ISSUE THREAD

**Issue by Osmosis-Wrench** [Sairion350/ORomance#1]
Talked about in discord link here: https://discord.com/channels/771971253199699988/771971758047494145/842044524200591401

Message text:
cant replicate the "bug": have lucien and serana, no one romance'd. DG questline since leaving eldergleam serana just straight went away. some moveto player brought her back, but she instantly turned around and went off ... but not in whiterun where she stood steadfast in front of warmaidens. after an oromance - seduce with a finished scene shes apparently back to normal

After investigating this a bit with the user, we were able to work out that Serana had the ORomancePlayerWaitPackage applied to them despite not having use ORomance on them at any point in the users memory. This happened after a scene where the user (via SDA) kissed Serana for a quest line. After that Serana immediately walked to Whiterun.

I think this might be related to FollowerSetThread.

**Comment by Sairion350** [comment]
This package is tied to an alias so barring some obscure engine bug, talking to anyone npc with oromance should unstuck it immediately, since the alias will get replaced...

Since everyone's game is configured different and some people just straight up modify my mods directly (ie flag as esl) i usually need 2 people to report a bug before i get deep into it.

**Comment by Osmosis-Wrench** [comment]
Fair enough, if it comes back up again somebody can reopen the case.
